/**
 * Generate a unified diff from Monaco's line changes.
 */
export function generateUnifiedDiff(originalText, modifiedText, lineChanges, filename = 'file') {
  const originalLines = originalText.split('\n');
  const modifiedLines = modifiedText.split('\n');

  const lines = [];
  lines.push(`--- a/${filename}`);
  lines.push(`+++ b/${filename}`);

  if (!lineChanges || lineChanges.length === 0) {
    // No changes
    return lines.join('\n');
  }

  for (const change of lineChanges) {
    const origStart = change.originalStartLineNumber;
    const origEnd = change.originalEndLineNumber;
    const modStart = change.modifiedStartLineNumber;
    const modEnd = change.modifiedEndLineNumber;

    // Context lines before the hunk
    const contextBefore = 3;
    const contextAfter = 3;

    const hunkOrigStart = Math.max(1, origStart - contextBefore);
    const hunkOrigEnd = Math.min(originalLines.length, (origEnd || origStart) + contextAfter);
    const hunkModStart = Math.max(1, modStart - contextBefore);
    const hunkModEnd = Math.min(modifiedLines.length, (modEnd || modStart) + contextAfter);

    const origCount = origEnd === 0 ? 0 : origEnd - origStart + 1;
    const modCount = modEnd === 0 ? 0 : modEnd - modStart + 1;

    const totalOrigLines = (hunkOrigStart < origStart ? origStart - hunkOrigStart : 0) + origCount + contextAfter;
    const totalModLines = (hunkModStart < modStart ? modStart - hunkModStart : 0) + modCount + contextAfter;

    lines.push(`@@ -${hunkOrigStart},${Math.min(totalOrigLines, originalLines.length - hunkOrigStart + 1)} +${hunkModStart},${Math.min(totalModLines, modifiedLines.length - hunkModStart + 1)} @@`);

    // Context before
    for (let i = hunkOrigStart; i < origStart && i <= originalLines.length; i++) {
      lines.push(` ${originalLines[i - 1]}`);
    }

    // Removed lines
    if (origEnd > 0) {
      for (let i = origStart; i <= origEnd && i <= originalLines.length; i++) {
        lines.push(`-${originalLines[i - 1]}`);
      }
    }

    // Added lines
    if (modEnd > 0) {
      for (let i = modStart; i <= modEnd && i <= modifiedLines.length; i++) {
        lines.push(`+${modifiedLines[i - 1]}`);
      }
    }

    // Context after
    const afterStart = (origEnd || origStart) + 1;
    for (let i = afterStart; i < afterStart + contextAfter && i <= originalLines.length; i++) {
      lines.push(` ${originalLines[i - 1]}`);
    }
  }

  return lines.join('\n');
}

/**
 * Generate a self-contained HTML diff document.
 */
export function generateHtmlDiff(originalText, modifiedText, lineChanges) {
  const originalLines = originalText.split('\n');
  const modifiedLines = modifiedText.split('\n');

  // Build a set of changed line numbers
  const removedLines = new Set();
  const addedLines = new Set();

  if (lineChanges) {
    for (const change of lineChanges) {
      if (change.originalEndLineNumber > 0) {
        for (let i = change.originalStartLineNumber; i <= change.originalEndLineNumber; i++) {
          removedLines.add(i);
        }
      }
      if (change.modifiedEndLineNumber > 0) {
        for (let i = change.modifiedStartLineNumber; i <= change.modifiedEndLineNumber; i++) {
          addedLines.add(i);
        }
      }
    }
  }

  const escapeHtml = (str) => str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  let html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Diff - Generated by Diff Please</title>
<style>
  body { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; margin: 0; padding: 20px; background: #0d1117; color: #c9d1d9; font-size: 13px; }
  .diff-container { display: grid; grid-template-columns: 1fr 1fr; gap: 2px; max-width: 100%; }
  .diff-pane { overflow-x: auto; }
  .diff-header { padding: 8px 12px; background: #161b22; border-bottom: 1px solid #30363d; font-weight: 600; color: #8b949e; }
  .line { display: flex; min-height: 20px; line-height: 20px; }
  .line-num { min-width: 50px; padding: 0 8px; text-align: right; color: #484f58; user-select: none; flex-shrink: 0; }
  .line-content { padding: 0 8px; white-space: pre-wrap; word-break: break-all; flex: 1; }
  .removed { background: #2d1618; }
  .removed .line-content { background: rgba(202, 24, 21, 0.3); }
  .added { background: #102820; }
  .added .line-content { background: rgba(46, 160, 67, 0.3); }
  h2 { margin: 0 0 16px; font-size: 14px; color: #8b949e; }
</style>
</head>
<body>
<h2>Generated by <a href="https://diffplease.com" style="color:#58a6ff">Diff Please</a></h2>
<div class="diff-container">
<div class="diff-pane">
<div class="diff-header">Original</div>`;

  for (let i = 0; i < originalLines.length; i++) {
    const lineNum = i + 1;
    const cls = removedLines.has(lineNum) ? ' removed' : '';
    html += `<div class="line${cls}"><span class="line-num">${lineNum}</span><span class="line-content">${escapeHtml(originalLines[i])}</span></div>`;
  }

  html += `</div>
<div class="diff-pane">
<div class="diff-header">Modified</div>`;

  for (let i = 0; i < modifiedLines.length; i++) {
    const lineNum = i + 1;
    const cls = addedLines.has(lineNum) ? ' added' : '';
    html += `<div class="line${cls}"><span class="line-num">${lineNum}</span><span class="line-content">${escapeHtml(modifiedLines[i])}</span></div>`;
  }

  html += `</div>
</div>
</body>
</html>`;

  return html;
}

/**
 * Download a string as a file.
 */
export function downloadFile(content, filename, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Copy text to clipboard.
 */
export async function copyToClipboard(text) {
  await navigator.clipboard.writeText(text);
}
